BeestjeOpJeFeestje/Controllers/AnimalController.cs
using BeestjeOpJeFeestje.Data.Models;
using BeestjeOpJeFeestje.Services.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.Controllers
{
    [Authorize(Roles = "Admin")]

    public class AnimalController : Controller
    {
        private readonly AnimalService _beestjeService;

        public AnimalController(BeestjeOpJeFeestjeContext context)
        {
            _beestjeService = new AnimalService(context);
        }

        public IActionResult Index()
        {
            var animals = _beestjeService.GetAnimals();

            return View(animals);
        }

        public IActionResult Create()
        {
            var animalTypes = _beestjeService.getAnimalTypes();

            ViewData["animalTypes"] = animalTypes;
            return View(new Animal());
        }

        [HttpPost]
        public IActionResult Create(Animal animal)
        {
            _beestjeService.CreateAnimal(animal);
            return RedirectToAction("Index");
        }

        public IActionResult Read(int id)
        {
            Animal animal = _beestjeService.GetAnimal(id);

            List<Booking>? bookings = _beestjeService.GetAnimalBookings(animal);

            ViewData["bookings"] = bookings;
            return View(animal);
        }

        public IActionResult Update(int id)
        {
            Animal animal = _beestjeService.GetAnimal(id);

            var animalTypes = _beestjeService.getAnimalTypes();

            ViewData["animalTypes"] = animalTypes;
            return View(animal);
        }

        [HttpPost]
        public IActionResult Update(Animal animal)
        {
            _beestjeService.UpdateAnimal(animal);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id) 
        {
            Animal animal = _beestjeService.GetAnimal(id);

            return View(animal);
        }

        [HttpPost]
        public IActionResult Delete(Animal animal)
        {
            _beestjeService.DeleteAnimal(animal);
            return RedirectToAction("Index");
        }
    }
}

BeestjeOpJeFeestje/Controllers/AuthController.cs
using BeestjeOpJeFeestje.Data.Models;
using BeestjeOpJeFeestje.Data.Models.ViewModels;
using BeestjeOpJeFeestje.Services.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.Controllers;

[Authorize]
public class AuthController : Controller
{
    private readonly AuthService _authService;

    public AuthController(UserManager<Account> userManager, SignInManager<Account> signInManager)
    {
        _authService = new AuthService(userManager, signInManager);
    }

    [AllowAnonymous]
    public IActionResult Login(string? returnUrl)
    {
        LoginViewModel viewModel = new LoginViewModel()
        {
            ReturnUrl = returnUrl
        };

        return View(viewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    [AllowAnonymous]
    public async Task<IActionResult> Login(LoginViewModel viewModel)
    {
        if (!ModelState.IsValid)
            return View(viewModel);

        if (!await _authService.Login(viewModel.Email, viewModel.Password))
        {
            TempData["Error"] = "Het e-mailadres of wachtwoord is onjuist.";

            return View(viewModel);
        }

        if (string.IsNullOrEmpty(viewModel.ReturnUrl))
            return RedirectToAction("Index", "Home");

        return Redirect(viewModel.ReturnUrl);
    }

    public async Task<IActionResult> Logout()
    {
        await _authService.Logout();

        return RedirectToAction("Index", "Home");
    }
}

BeestjeOpJeFeestje/Controllers/UserBookingsController.cs
using BeestjeOpJeFeestje.Data.Models;
using BeestjeOpJeFeestje.Data.Models.ViewModels.Booking;
using BeestjeOpJeFeestje.Services.Services;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BeestjeOpJeFeestje.Controllers;

public class UserBookingsController : Controller
{
    private readonly BookingService _bookingService;
    private readonly UserManager<Account> _userManager;

    public UserBookingsController(BeestjeOpJeFeestjeContext context, UserManager<Account> userManager)
    {
        _bookingService = new BookingService(context);
        _userManager = userManager;
    }

    public async Task<IActionResult> Index()
    {
        Account? user = await _userManager.GetUserAsync(User);

        if (user == null)
            return RedirectToAction("Index", "Home");

        List<Booking> bookings = _bookingService.GetAllUserBookings(user);
        List<ViewOwnBookingViewModel> viewModels = bookings
            .Select(booking => new ViewOwnBookingViewModel
            {
                Booking = booking,
                TotalDiscount = _bookingService.GetTotalDiscount(_bookingService.GetDiscounts(booking)),
                Discounts = _bookingService.GetDiscounts(booking),
                Price = _bookingService.GetPriceAfterDiscounts(booking)
            })
            .ToList();

        return View(viewModels);
    }

    public IActionResult View(int id)
    {
        Booking? booking = _bookingService.GetBookingById(id);

        if (booking == null)
            return RedirectToAction("Index");

        ViewOwnBookingViewModel viewModel = new ViewOwnBookingViewModel
        {
            Booking = booking,
            TotalDiscount = _bookingService.GetTotalDiscount(_bookingService.GetDiscounts(booking)),
            Discounts = _bookingService.GetDiscounts(booking),
            Price = _bookingService.GetPriceAfterDiscounts(booking)
        };

        return View(viewModel);
    }

    public IActionResult Delete(int id)
    {
        Booking? booking = _bookingService.GetBookingById(id);

        if (booking == null)
            return RedirectToAction("Index");

        return View(booking);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult DeleteConfirmed(int id)
    {
        Booking? booking = _bookingService.GetBookingById(id);

        if (booking != null)
            _bookingService.DeleteBooking(booking);

        return RedirectToAction("Index");
    }
}

BeestjeOpJeFeestje/Views/Shared/_BookingStepProgress.cshtml
@model int

<section id="booking-progress">
    <div class="row">
        <div class="col booking-step @(Model == 1 ? "active-booking-step" : "") d-flex flex-column justify-content-center position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div class="booking-step-number position-relative">
                    <span class="position-absolute top-50 start-50 translate-middle">
                        1
                    </span>
                </div>

                <span class="booking-step-title">
                    Beestjes
                </span>
            </div>
        </div>
        
        <div class="col booking-step @(Model == 2 ? "active-booking-step" : "") d-flex flex-column justify-content-center position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div class="booking-step-number position-relative">
                    <span class="position-absolute top-50 start-50 translate-middle">
                        2
                    </span>
                </div>

                <span class="booking-step-title">
                    Gegevens
                </span>
            </div>
        </div>
        
        <div class="col booking-step @(Model == 3 ? "active-booking-step" : "") d-flex flex-column justify-content-center position-relative">
            <div class="position-absolute top-50 start-50 translate-middle">
                <div class="booking-step-number position-relative">
                    <span class="position-absolute top-50 start-50 translate-middle">
                        3
                    </span>
                </div>

                <span class="booking-step-title">
                    Bevestiging
                </span>
            </div>
        </div>
    </div>
</section>

BeestjeOpJeFeestje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <title>@ViewData["Title"] - BeestjeOpJeFeestje</title>

        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/BeestjeOpJeFeestje.styles.css" asp-append-version="true" />
        @await RenderSectionAsync("Styles", required: false)
    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BeestjeOpJeFeestje</a>

                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Boeken</a>
                            </li>

                            @if (User.Identity?.IsAuthenticated == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="UserBookings" asp-action="Index">Mijn boekingen</a>
                                </li>

                                @if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item dropdown">
                                        <a class="nav-link dropdown-toggle text-dark" href="#" id="accountDropdown" data-bs-toggle="dropdown">
                                            Accounts
                                        </a>

                                        <ul class="dropdown-menu" aria-labelledby="accountDropdown">
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Index">Overview</a></li>
                                            <li><a class="dropdown-item" asp-area="" asp-controller="Account" asp-action="Create">Create</a></li>
                                        </ul>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Beestjes</a>
                                    </li>
                                }
                            }
                        </ul>
                        
                        <ul class="navbar-nav">
                            @if (User.Identity?.IsAuthenticated == true)
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
            </nav>
        </header>

        <div class="container">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2025 - Jordi Keijzers & Wessel de Heus
            </div>
        </footer>

        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <partial name="_ValidationScriptsPartial"/>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>